# Generated by Django 3.0 on 2020-06-25 08:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20200625_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('tech', 'TECH'), ('class_mus', 'CLASSICAL MUSIC'), ('gen', 'GENERAL'), ('gen_music', 'GENERAL MUSIC'), ('novels', 'NOVELS'), ('physics', 'PHYSICS'), ('maths', 'MATHS')], default='notes', max_length=30)),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(default='/media/files/git.txt', storage=django.core.files.storage.FileSystemStorage(location='/media/audio/'), upload_to='files')),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('tech', 'TECH'), ('class_mus', 'CLASSICAL MUSIC'), ('gen', 'GENERAL'), ('gen_music', 'GENERAL MUSIC'), ('novels', 'NOVELS'), ('physics', 'PHYSICS'), ('maths', 'MATHS')], default='notes', max_length=30)),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(default='/media/files/git.txt', storage=django.core.files.storage.FileSystemStorage(location='/media/images/'), upload_to='files')),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('tech', 'TECH'), ('class_mus', 'CLASSICAL MUSIC'), ('gen', 'GENERAL'), ('gen_music', 'GENERAL MUSIC'), ('novels', 'NOVELS'), ('physics', 'PHYSICS'), ('maths', 'MATHS')], default='notes', max_length=30)),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(default='/media/files/git.txt', storage=django.core.files.storage.FileSystemStorage(location='/media/notes/'), upload_to='files')),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('tech', 'TECH'), ('class_mus', 'CLASSICAL MUSIC'), ('gen', 'GENERAL'), ('gen_music', 'GENERAL MUSIC'), ('novels', 'NOVELS'), ('physics', 'PHYSICS'), ('maths', 'MATHS')], default='notes', max_length=30)),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(default='/media/files/git.txt', storage=django.core.files.storage.FileSystemStorage(location='/media/video/'), upload_to='files')),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
