# Generated by Django 3.0 on 2020-06-26 22:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20200626_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='file_pic',
            field=models.FileField(default='/media/image/', storage=django.core.files.storage.FileSystemStorage(location='/media/image/'), upload_to='image'),
        ),
        migrations.AddField(
            model_name='image',
            name='file_pic',
            field=models.FileField(default='/media/image/', storage=django.core.files.storage.FileSystemStorage(location='/media/image/'), upload_to='image'),
        ),
        migrations.AddField(
            model_name='note',
            name='file_pic',
            field=models.FileField(default='/media/image/', storage=django.core.files.storage.FileSystemStorage(location='/media/image/'), upload_to='image'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_pic',
            field=models.FileField(default='/media/image/', storage=django.core.files.storage.FileSystemStorage(location='/media/image/'), upload_to='image'),
        ),
    ]
